# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://oxizen-pro.github.io
title: www.oxizen.pro
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2015 www.oxizen.pro. All Rights Reserved.'
credits: 'Credits: <a href="http://oxizen.pro">www.oxizen.pro</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: linkedin
    url: 
  - title: E-Mail
    url: "mailto: admin@flixart.pro"
